### ISSUE TITLE
Out of Memory error when training on big number of classes

### ISSUE THREAD

**Issue by fnourry** [idstcv/SoftTriple#11]
Hello, I'm trying to train the network on a dataset of 8k+ classes and I have this error:

`RuntimeError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 11.17 GiB total capacity; 10.68 GiB already allocated; 11.31 MiB free; 10.72 GiB reserved in total by PyTorch)
`
I use a Tesla K80. When training on 3k classes or less everything is fine. The limit of classes seems to be around 3k/4k. I don't think this is a matter of number of images since reducing the batch size doesn't fix the error.

Did you try to run it with a big number of classes ? Any ways to reduce the memory allocated ?

Thanks !

**Comment by qian-qi** [comment]
We can run it on SOP which contains more than 10k classes. Maybe you can try to reduce the number of centers K.

**Comment by fnourry** [comment]
Thank you for your answer, it seems to be working
