### ISSUE TITLE
Clarification on gamma and lambda

### ISSUE THREAD

**Issue by lindsey98** [idstcv/SoftTriple#12]
Hi Qi Qian, 
   I like your paper, especially the elegant derivation part. Can I have some clarifications on gamma and lambda: 
   From my understanding, gamma and lambda can also be viewed as the temperature in SoftMax, which controls how concentrated/spread of intra-class similarity and inter-class similarity. I noticed that you let gamma to be 0.1, and 1/lambda to be 0.2. Which means you want intra-class similarly distribution to be very concentrated, and inter-class similarity distribution to be relatively a little bit smoother, is my understanding correct? Also do you require gamma and 1/lambda to be less than 1 to give a low temperature to avoid over-smoothing?
   Thanks!

**Comment by qian-qi** [comment]
Hi, thank you for your interest. We actually have lambda=20, which means a large margin between each classes and a smooth distribution within each class. Those parameters are usually set to be small for discrimination.

**Comment by lindsey98** [comment]
Ok thanks for your reply
