### ISSUE TITLE
can you explain the recall@k?

### ISSUE THREAD

**Issue by youmingdeng** [idstcv/SoftTriple#6]
Hello, I'm very interested in your deep metric learning work.
the code in evaluation:
    YNN = Y[indices]
    for i in range(0, len(Kset)):
        pos = 0.
        for j in range(0, num):
            if Y[j] in YNN[j, :Kset[i]]:
                pos += 1.
        recallK[i] = pos/num
    return nmi, recallK
This looks more like computing **Rank-k**
Can you explain why compute the recall@k in this way? Thanks!
the relevant document of recall@k: 
https://ils.unc.edu/courses/2013_spring/inls509_001/lectures/10-EvaluationMetrics.pdf

**Comment by qian-qi** [comment]
Hi,

Thank you for your interest. We have mentioned in our paper that we followed the formulation in other work [1] for a fair comparison.

[1]CVPR'16: Deep Metric Learning via Lifted Structured Feature Embedding

**Comment by youmingdeng** [comment]
I see, thank you.
