### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by QuanNguyen94** [idstcv/SoftTriple#7]
Thank for all your contributions. I wonder that SoftTriple can work on oneshot problem or not ? And do you have any pretrained models ?

**Comment by qian-qi** [comment]
Hi,
Thank you for your interest. The proposed loss is for the standard metric learning, so it can be applied for learning the generic features, which can be used for other tasks.
I don't prepare pretrained models since it only costs several hours to train a model on the benchmark data set.

**Comment by QuanNguyen94** [comment]
Got it, thanks !
