### ISSUE TITLE
out of memory error

### ISSUE THREAD

**Issue by QianshengGu** [idstcv/SoftTriple#8]
Hi, @qian-qi 
I run your codes with default settings on a single Tesla-v100 card, but an error occurred

"RuntimeError: CUDA out of memory. Tried to allocate 10.52 GiB (GPU 0; 31.72 GiB total capacity; 22.42 GiB already allocated; 8.18 GiB free; 15.33 MiB cached)"

Why the softtriple loss costs such many memory? Or can you share your experimental settings in details? Thank you.

**Comment by qian-qi** [comment]
Hi,
It costs less than 3GB memories with default settings in my environment, which is a single P100.

**Comment by QianshengGu** [comment]
Hi,
I just change the "self.weight = torch.zeros(cLass_num*K, cLass_num*K, dtype=torch.bool).cuda()" to "self.weight = torch.zeros(cLass_num*K, cLass_num*K, dtype=torch.long).cuda()", as torch.bool is not supported in torch 1.0.1, it that matters?

**Comment by qian-qi** [comment]
Pls try torch.uint8 instead.

**Comment by QianshengGu** [comment]
Hi,
It works, thx!
